--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jacob3105/MagicStick
build-by-default: true
branches:
- main
projects:
  MagicStick:
    path: ""
    icon: icon.gif
    libs:
      - src: NhanAZ/libBedrock/libBedrock
        version: 1.1.7
...
